version: '3.1'

services:

  db:
    image: mysql
    container_name: enzo-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    container_name: enzo-adminer
    restart: always
    ports:
      - 6060:8080

  web:
   container_name: enzo-web
   image: webdevops/php-apache
   restart: always
   ports:
     - 6061:80
   volumes:
     - ../joomla:/app
